# Generated by Django 5.1.7 on 2025-04-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('materiales', models.TextField(help_text='Separados por comas')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
