# Generated by Django 5.1.7 on 2025-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='construcciones/'),
        ),
    ]
