# Generated by Django 5.1.7 on 2025-04-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_flora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flora',
            name='numero',
        ),
    ]
