from django.urls import path
from .views import (
    home,
    enemigos,
    consumibles,
    historia,
    forowiki,
    inicio_sesion_wiki,
    micuentatf,
    recuperarcontra,
    registrase,
    cerrar_sesion,
    construcciones,
    eliminar_construccion,
    editar_construccion,
    crear_construccion,
    animales,
    eliminar_animal,
    editar_animal,
    crear_animal,
    lugares_view,
    crear_lugar,
    editar_lugar,
    eliminar_lugar,
    crear_enemigo,
    editar_enemigo,
    eliminar_enemigo,
    flora,
    crear_flora,
    editar_flora,
    eliminar_flora,
    armas,
    crear_arma,
    editar_arma,
    eliminar_arma,
)

urlpatterns = [
    path("", home, name="home"),
    path("enemigos", enemigos, name="enemigos"),
    path("flora", flora, name="flora"),
    path("consumibles", consumibles, name="consumibles"),
    path("historia", historia, name="historia"),
    path("forowiki", forowiki, name="forowiki"),
    path("inicio_sesion_wiki", inicio_sesion_wiki, name="inicio_sesion_wiki"),
    path("micuentatf", micuentatf, name="micuentatf"),
    path("recuperarcontra", recuperarcontra, name="recuperarcontra"),
    path("registrase", registrase, name="registrase"),
    path("logout", cerrar_sesion, name="logout"),
    path("construcciones", construcciones, name="construcciones"),
    path('construcciones/eliminar/<int:pk>', eliminar_construccion, name='eliminar_construccion'),
    path('construccion/<int:id>/editar', editar_construccion, name='editar_construccion'),
    path('construccion/crear', crear_construccion, name='crear_construccion'),
    path('animales', animales, name='animales'),
    path('animales/crear', crear_animal, name='crear_animal'),
    path('animales/editar/<int:animal_id>', editar_animal, name='editar_animal'),
    path('animales/eliminar/<int:animal_id>', eliminar_animal, name='eliminar_animal'),
    path('lugares', lugares_view, name='lugares_view'),
    path('lugares/crear', crear_lugar, name='crear_lugar'),
    path('lugares/editar/<int:lugar_id>', editar_lugar, name='editar_lugar'),
    path('lugares/eliminar/<int:lugar_id>', eliminar_lugar, name='eliminar_lugar'),
    path("enemigos", enemigos, name="enemigos"),
    path("enemigos/crear", crear_enemigo, name="crear_enemigo"),
    path("enemigos/editar/<int:enemigo_id>", editar_enemigo, name="editar_enemigo"),
    path("enemigos/eliminar/<int:enemigo_id>", eliminar_enemigo, name="eliminar_enemigo"),
    path("flora", flora, name="flora"),
    path("flora/crear", crear_flora, name="crear_flora"),
    path("flora/editar/<int:flora_id>", editar_flora, name="editar_flora"),
    path("flora/eliminar/<int:flora_id>", eliminar_flora, name="eliminar_flora"),
    path('armas', armas, name='armas'),
    path('armas/crear', crear_arma, name='crear_arma'),
    path('armas/editar/<int:arma_id>', editar_arma, name='editar_arma'),
    path('armas/eliminar/<int:arma_id>', eliminar_arma, name='eliminar_arma'),
]
