from django.urls import path
from .views import (
    home,
    animales,
    enemigos,
    construcciones,
    flora,
    armas,
    consumibles,
    historia,
    forowiki,
    inicio_sesion_wiki,
    micuentatf,
    recuperarcontra,
    registrase,
    cerrar_sesion,
    eliminar_construccion,
    editar_construccion,
    crear_construccion,
    eliminar_animal,
    editar_animal,
    crear_animal,
    lugares_view,
    crear_lugar,
    editar_lugar,
    eliminar_lugar,
)

urlpatterns = [
    path("", home, name="home"),
    path("enemigos", enemigos, name="enemigos"),
    path("flora", flora, name="flora"),
    path("armas", armas, name="armas"),
    path("consumibles", consumibles, name="consumibles"),
    path("historia", historia, name="historia"),
    path("forowiki", forowiki, name="forowiki"),
    path("inicio_sesion_wiki", inicio_sesion_wiki, name="inicio_sesion_wiki"),
    path("micuentatf", micuentatf, name="micuentatf"),
    path("recuperarcontra", recuperarcontra, name="recuperarcontra"),
    path("registrase", registrase, name="registrase"),
    path("logout", cerrar_sesion, name="logout"),
    path("construcciones", construcciones, name="construcciones"),
    path('construcciones/eliminar/<int:pk>', eliminar_construccion, name='eliminar_construccion'),
    path('construccion/<int:id>/editar', editar_construccion, name='editar_construccion'),
    path('construccion/crear', crear_construccion, name='crear_construccion'),
    path('animales', animales, name='animales'),
    path('animales/crear', crear_animal, name='crear_animal'),
    path('animales/editar/<int:animal_id>', editar_animal, name='editar_animal'),
    path('animales/eliminar/<int:animal_id>', eliminar_animal, name='eliminar_animal'),
    path('lugares', lugares_view, name='lugares_view'),
    path('lugares/crear', crear_lugar, name='crear_lugar'),
    path('lugares/editar/<int:lugar_id>', editar_lugar, name='editar_lugar'),
    path('lugares/eliminar/<int:lugar_id>', eliminar_lugar, name='eliminar_lugar'),
    
]
